# PepperMint Theme Configuration
[theme]
name = "Gameboy Green (Dark)"
developer = "Peppermints"
dark_mode = true
encrypted = false

[colors]
primary = "#606E00"
secondary = "#ACC700"
background = "#FFFFFF"
foreground = "#747474"